language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
        - mkdir ~/.linuxbrew/bin
        - ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
        - eval $(~/.linuxbrew/bin/brew shellenv)
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_isntall:
        - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
install: 
 - brew install youtube-dl
 - pip3 install scipy audiotsm pillow
script: python3 auto-editor.py --help || python auto-editor.py --help
