language: python
python:
  - "3.8"
install:
  - git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
  - mkdir ~/.linuxbrew/bin
  - ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
  - eval $(~/.linuxbrew/bin/brew shellenv)
  - brew install youtube-dl
  - pip3 install numpy scipy audiotsm opencv-python
script:
  - python auto-editor.py --help
