name: build
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.png'
      - 'setup.py'
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.8']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run
      run:   |
             if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo apt update
                  sudo apt install ffmpeg
                  python3 -m pip install --upgrade pip
                  python3 -m pip install av opencv-python audiotsm2
                  python3 -m auto_editor test
             else
                  py -m pip install --upgrade pip
                  py -m pip install av opencv-python audiotsm2
                  py -m auto_editor test
             fi
      shell: bash
